export type TravelSuggestion = {
  label: string;
  code: string;
  hint: string;
};

export const AIRPORT_SUGGESTIONS: TravelSuggestion[] = [
  { label: "Delhi", code: "DEL", hint: "Indira Gandhi International" },
  { label: "Guwahati", code: "GAU", hint: "Lokpriya Gopinath Bordoloi" },
  { label: "Kolkata", code: "CCU", hint: "Netaji Subhas Chandra Bose" },
  { label: "Mumbai", code: "BOM", hint: "Chhatrapati Shivaji Maharaj" },
  { label: "Bengaluru", code: "BLR", hint: "Kempegowda International" },
  { label: "Chennai", code: "MAA", hint: "Chennai International" },
  { label: "Hyderabad", code: "HYD", hint: "Rajiv Gandhi International" },
  { label: "Jaipur", code: "JAI", hint: "Jaipur International" },
  { label: "Goa", code: "GOI", hint: "Manohar International" },
  { label: "Kochi", code: "COK", hint: "Cochin International" },
  { label: "Thiruvananthapuram", code: "TRV", hint: "Trivandrum International" },
  { label: "Srinagar", code: "SXR", hint: "Sheikh Ul-Alam" },
  { label: "Bagdogra", code: "IXB", hint: "Gateway to North Bengal" },
  { label: "Dibrugarh", code: "DIB", hint: "Mohanbari Airport" },
  { label: "Jorhat", code: "JRH", hint: "Rowriah Airport" },
  { label: "Silchar", code: "IXS", hint: "Kumbhirgram Airport" },
  { label: "Dimapur", code: "DMU", hint: "Dimapur Airport" },
  { label: "Agartala", code: "IXA", hint: "Maharaja Bir Bikram" },
  { label: "Imphal", code: "IMF", hint: "Bir Tikendrajit International" },
  { label: "Port Blair", code: "IXZ", hint: "Veer Savarkar International" },
  { label: "Pune", code: "PNQ", hint: "Pune Airport" },
  { label: "Ahmedabad", code: "AMD", hint: "Sardar Vallabhbhai Patel" },
  { label: "Varanasi", code: "VNS", hint: "Lal Bahadur Shastri" },
  { label: "Udaipur", code: "UDR", hint: "Maharana Pratap" },
  { label: "Nagpur", code: "NAG", hint: "Dr. Babasaheb Ambedkar" },
  { label: "Ranchi", code: "IXR", hint: "Birsa Munda Airport" },
];

export const RAILWAY_SUGGESTIONS: TravelSuggestion[] = [
  { label: "New Delhi", code: "NDLS", hint: "New Delhi Railway Station" },
  { label: "Guwahati", code: "GHY", hint: "Guwahati Railway Station" },
  { label: "Howrah", code: "HWH", hint: "Howrah Junction" },
  { label: "Sealdah", code: "SDAH", hint: "Sealdah Railway Station" },
  { label: "Mumbai Central", code: "MMCT", hint: "Mumbai Central" },
  { label: "CSMT Mumbai", code: "CSMT", hint: "Chhatrapati Shivaji Maharaj Terminus" },
  { label: "Bengaluru City", code: "SBC", hint: "Krantivira Sangolli Rayanna" },
  { label: "Chennai Central", code: "MAS", hint: "Puratchi Thalaivar Dr. MGR Central" },
  { label: "Jaipur", code: "JP", hint: "Jaipur Junction" },
  { label: "Varanasi", code: "BSB", hint: "Varanasi Junction" },
  { label: "Patna", code: "PNBE", hint: "Patna Junction" },
  { label: "Lucknow", code: "LKO", hint: "Lucknow NR" },
  { label: "Agra Cantt", code: "AGC", hint: "Agra Cantt Railway Station" },
  { label: "Bhopal", code: "BPL", hint: "Bhopal Junction" },
  { label: "Pune", code: "PUNE", hint: "Pune Junction" },
  { label: "Ahmedabad", code: "ADI", hint: "Ahmedabad Junction" },
  { label: "Ernakulam", code: "ERS", hint: "Ernakulam Junction" },
  { label: "Thiruvananthapuram Central", code: "TVC", hint: "TVM Central" },
  { label: "Chandigarh", code: "CDG", hint: "Chandigarh Railway Station" },
  { label: "Amritsar", code: "ASR", hint: "Amritsar Junction" },
  { label: "Jodhpur", code: "JU", hint: "Jodhpur Junction" },
  { label: "Udaipur City", code: "UDZ", hint: "Udaipur City Railway Station" },
  { label: "Siliguri", code: "SGUJ", hint: "Siliguri Junction" },
  { label: "Dibrugarh", code: "DBRG", hint: "Dibrugarh Railway Station" },
  { label: "Dimapur", code: "DMV", hint: "Dimapur Railway Station" },
  { label: "Kolkata", code: "KOAA", hint: "Kolkata Terminal" },
];
